### ISSUE TITLE
[Suggestion] ChannelDms resizeable upwards 

### ISSUE THREAD

**Issue by L-Ratio** [maenDisease/BetterDiscordStuff#1]
It resizes it rtl and ltr perfectly fine but would it be possible to have it resize upwards and still have the message box follow it?

**Comment by maenDisease** [comment]
Added in [64f62e5](https://github.com/maenDisease/BetterDiscordStuff/commit/64f62e5f339d53bfdd6134fb069741718d8260f3), drag the bottom right corner
