### ISSUE TITLE
BD Server Store CSS 

### ISSUE THREAD

**Issue by iGetUploaded** [maenDisease/BetterDiscordStuff#11]
I'm going to assume its not supposed to look like this? or am I wrong

![image](https://user-images.githubusercontent.com/54633753/195234706-26caea29-7474-4f34-8244-b0a871821efb.png)

**Comment by maenDisease** [comment]
Supposed to look like that

**Comment by iGetUploaded** [comment]
Oh okay wasnt sure if the gap on the right side was supposed to be there or not ty
