### ISSUE TITLE
Disable Minimum Size warning message

### ISSUE THREAD

**Issue by Bad3r** [maenDisease/BetterDiscordStuff#12]
Hey there! 👋
thanks for the awesome theme!

one thing that been bugging me is this warning which shows up even though I have Minimum size removed. Is there a way to completely disable it?
![image](https://user-images.githubusercontent.com/25513724/215295241-d0a8cc48-4d67-46ff-8ca5-173c9cc059d0.png)

**Comment by maenDisease** [comment]
remove the minimum size line inside the theme file

**Comment by Bad3r** [comment]
@maenDisease I can't locate the line you mentioned.

I do not see any mention of 'minimum' size in [https://github.com/maenDisease/BetterDiscordStuff/blob/main/Themes/Float/Float.css](https://github.com/maenDisease/BetterDiscordStuff/blob/main/Themes/Float/Float.css).

**Comment by maenDisease** [comment]
The theme file, not source file
