### ISSUE TITLE
Not being apple to click on AppNotifications Toast

### ISSUE THREAD

**Issue by j10a1n15** [maenDisease/BetterDiscordStuff#14]
While using this Theme and the [AppNotifications ](https://github.com/QWERTxD/BetterDiscordPlugins/blob/main/InAppNotifications/InAppNotifications.plugin.js)Plugin I am almost unable to click on the Toast to get directed to the channel where the message was send in. This only seems to be accuring with this theme on

**Comment by maenDisease** [comment]
It's because of the channel bar being made draggable, not sure if there's much i can do about it besides removing having it draggable

**Comment by j10a1n15** [comment]
Okay just tried it, and it doenst seems to be fixable at first glance, thats sad
The message hitbox is just a little small sometimes, but I guess I have to get used to it
Still thank you!
