### ISSUE TITLE
Channel Tabs Lined - Removes title bar

### ISSUE THREAD

**Issue by BigFlubba** [maenDisease/BetterDiscordStuff#2]
Enabled:
![image](https://user-images.githubusercontent.com/69104450/158039394-e65ba31e-7c31-45a0-a656-18c45fa343b8.png)

Disabled:
![image](https://user-images.githubusercontent.com/69104450/158039395-53b7791a-7548-44f2-b323-9fc9c19d8d7e.png)

**Comment by maenDisease** [comment]
Do you have ChannelTabs enabled

**Comment by BigFlubba** [comment]
No.

**Comment by BigFlubba** [comment]
ChannelTabs doesn't work.

**Comment by maenDisease** [comment]
> ChannelTabs doesn't work.

This is not a ChannelTabsLined issue, refer the plugin’s support server or the BetterDiscord server. Try restarting Discord after the plugin is enabled.

**Comment by BigFlubba** [comment]
I know it's not, I was just saying that the plugin doesn't work.
