### ISSUE TITLE
[Float Bug] The little x icon in voice channels' integrated text cannels isn't present on smaller window sizes

### ISSUE THREAD

**Issue by lewo-liowa** [maenDisease/BetterDiscordStuff#22]
You have to resize the window to be able to remove the text channel from obscuring streams and such, which isn't very convenient.

![изображение](https://user-images.githubusercontent.com/42380920/233153255-16e1d566-84c4-4245-b5a9-5f99b860d7dd.png)
![изображение](https://user-images.githubusercontent.com/42380920/233153265-cdf9dd3a-62b6-4166-b8b1-3ddd4365c506.png)

**Comment by lewo-liowa** [comment]
Well, yeah, i just chekced and it's fixed now somehow.

**Comment by maenDisease** [comment]
[maenDisease/Float](https://github.com/maenDisease/Float) is under construction
