### ISSUE TITLE
[Question] Asking for permission to import CSS

### ISSUE THREAD

**Issue by OlavWolfiken** [maenDisease/BetterDiscordStuff#3]
### Hi there!

Been trying to reach you, to ask about a BD related thing.
Can I have your permission to use your [compact BD addon list CSS](https://github.com/maenDisease/BetterDiscordStuff/blob/main/css/bdAddonMini.css), as an import in a [theme](https://olavwolfiken.github.io/BetterDiscord/Themes/Simple%20Black%20Theme) I'm currently working on?
Thank you in advance, have a good rest of your day!

###### You can find me BD-related servers under the name @OlafHarlender#0134

**Comment by maenDisease** [comment]
Sure go ahead
