### ISSUE TITLE
[Suggestion] Make it compatible with HorizontalServerList plugin

### ISSUE THREAD

**Issue by reynoldyehezkiel** [maenDisease/BetterDiscordStuff#5]
![image](https://user-images.githubusercontent.com/73789263/181392509-1f7c201a-2b52-4b6c-89a8-8de7f4cfbdf7.png)
Just need to be rearranged

**Comment by maenDisease** [comment]
use bottom horizontal server list

**Comment by maenDisease** [comment]
Also HorizontalServerList is a theme, which is harder to provide compatibility between themes

**Comment by reynoldyehezkiel** [comment]
> use bottom horizontal server list

i'll try

**Comment by reynoldyehezkiel** [comment]
> Also HorizontalServerList is a theme, which is harder to provide singular compatibility between themes without having the user manually add the compatibility code

ok then, i close it

**Comment by GiacoAV** [comment]
Hi, sorry to reopen this issue but were can this "bottom horizontal server list" theme/plugin/addon be found ?
All i've found is the HorizontalServerList theme which is, as said here, bugged.
Thanks in advance :)

**Comment by reynoldyehezkiel** [comment]
here
![image](https://user-images.githubusercontent.com/73789263/182009727-7c391f25-ba9b-466e-8359-e11377cff442.png)
