### ISSUE TITLE
Issue with moving the window arround

### ISSUE THREAD

**Issue by Plamen662** [maenDisease/BetterDiscordStuff#7]
It is so cool, but after I type the custom CSS in it doesn't let me drag the window around. Is it possible to be draggable? 
Love your work, keep it up :)

**Comment by maenDisease** [comment]
which css does this refer to

**Comment by Plamen662** [comment]
"mac-titlebar.css"

**Comment by maenDisease** [comment]
that import is only specifically for the theme, and the channelheader is draggable

**Comment by Plamen662** [comment]
my bad then
