### ISSUE TITLE
Background?

### ISSUE THREAD

**Issue by LucidNyxx** [maenDisease/BetterDiscordStuff#8]
Well, not really an issue. I just want to know what is the link to the background image. Thanks!
![183326277-9e38fadc-1c27-495e-9eda-ba92ef4fc776](https://user-images.githubusercontent.com/80446279/186784664-69f27d89-325e-4007-9ae1-55efc407ef91.png)

**Comment by maenDisease** [comment]
The image for the theme has been edited and upscaled
Original: https://www.pixiv.net/en/artworks/83955949

**Comment by LucidNyxx** [comment]
Okay, cool. Thanks!
