### ISSUE TITLE
Solana theme user profile long

### ISSUE THREAD

**Issue by SpookieGames** [maenDisease/BetterDiscordStuff#9]
The user profile is long when clicked on in the members list

![image](https://user-images.githubusercontent.com/41782443/191292649-e2b1a71f-47ba-42a6-9c9b-2f38c9855b14.png)

**Comment by SpookieGames** [comment]
Tried with all plugin off but still happens

**Comment by maenDisease** [comment]
Discord made a major update to the banner code so I prepared the code in advance

**Comment by SpookieGames** [comment]
Seems to be fixed now

![image](https://user-images.githubusercontent.com/41782443/191342223-806b6110-eb64-4e97-9bb9-c5a5c1c60b9e.png)
